[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:cdn]
command=/cdn
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autostart=true
autorestart=true

[program:hlp]
command=/hlp
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
autostart=true
autorestart=true